//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEG.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TEG.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;World&gt;
        ///  &lt;Continent Name=&quot;Africa&quot; Bonus=&quot;3&quot; &gt;
        ///    &lt;Country Name=&quot;Egypt&quot; Neighbors=&quot;Sahara,Ethiopia,Madagascar,Israel,Turkey,Poland&quot;/&gt;
        ///    &lt;Country Name=&quot;Ethiopia&quot; Neighbors=&quot;Egypt,Sahara,Zaire,South Africa&quot;/&gt;
        ///    &lt;Country Name=&quot;Madagascar&quot; Neighbors=&quot;Egypt,Zaire&quot;/&gt;
        ///    &lt;Country Name=&quot;Sahara&quot; Neighbors=&quot;Egypt,Ethiopia,Zaire,Spain,Brazil&quot;/&gt;
        ///    &lt;Country Name=&quot;South Africa&quot; Neighbors=&quot;Zaire,Ethiopia&quot;/&gt;
        ///    &lt;Country Name=&quot;Zaire&quot; Neighbors=&quot;Sahara,Ethiopia,South A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Objectives&gt;
        ///  &lt;Objective Type=&quot;Common&quot;&gt;
        ///    &lt;Target Number=&quot;30&quot;/&gt;
        ///  &lt;/Objective&gt;
        ///  &lt;Objective Type=&quot;Occupy&quot;&gt;
        ///    &lt;Target Continent=&quot;Africa&quot; Number=&quot;-1&quot;/&gt;
        ///    &lt;Target Continent=&quot;North America&quot; Number=&quot;5&quot;/&gt;
        ///    &lt;Target Continent=&quot;Europe&quot; Number=&quot;4&quot;/&gt;
        ///  &lt;/Objective&gt;
        ///  &lt;Objective Type=&quot;Occupy&quot;&gt;
        ///    &lt;Target Continent=&quot;South America&quot; Number=&quot;-1&quot;/&gt;
        ///    &lt;Target Continent=&quot;Europe&quot; Number=&quot;7&quot;/&gt;
        ///    &lt;Target Continent=&quot;Asia&quot; Number=&quot;3&quot;/&gt;
        ///  &lt;/Objective&gt;
        ///  &lt;Objectiv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Objectives {
            get {
                return ResourceManager.GetString("Objectives", resourceCulture);
            }
        }
    }
}
